### ISSUE TITLE
What might be the cause for the inferiority to LiDAR-based methods?

### ISSUE THREAD

**Issue by npurson** [NVlabs/VoxFormer#1]
A concise solution towards camera-based SSC!
Yet, I'm still wondering what might be the cause for the inferiority to LiDAR-based methods like SSCNet & JS3CNet?

Since VoxFormer:

1. has already employed a depth estimator to obtain geometry information
2. able to perform on par with LiDAR-based methods at the range of 12.8 m, (I assume LiDAR helps more at close range?)

what else may make VoxFormer and other camera-based methods lag behind the LiDAR-based ones?

**Comment by segments-tobias** [comment]
I assume a big part of the problem is the reliance on 2D depth maps, since objects that are far away become very small in the depth map.
I do wonder what the authors have to say too :)

**Comment by Chrisding** [comment]
Getting accurate depth at long distances is a challenging problem for camera-based methods. This is where LiDAR-based method can help more. Well said by @segments-tobias .
