### ISSUE TITLE
About train and infer in indoor dataset?

### ISSUE THREAD

**Issue by someone-TJ** [NVlabs/VoxFormer#16]
How Can I train this model in NYUv2? I find the data format is so different from semantickitti

**Comment by someone-TJ** [comment]
Can this model be trained on NYU depth v2?

**Comment by RoboticsYimingLi** [comment]
You may refer to the dataloader in MonoScene (https://github.com/astra-vision/MonoScene/blob/master/monoscene/data/NYU/nyu_dataset.py) for NYUv2.
