### ISSUE TITLE
About the stage1 training

### ISSUE THREAD

**Issue by OrangeSodahub** [NVlabs/VoxFormer#20]
According to your paper:
![image](https://user-images.githubusercontent.com/54439582/230539508-39749010-be7b-4140-ba1c-abbf54b8ccd5.png)
You output the query proposal based on the depth prediction, however I saw in your released code that you used `LMSCNet` to generate the proposal, is it a misalignment? It seems that `LMSCNet` didn't generate a depth prediction, but got lidar input and output the class-specified results. Look forward to your reply!

**Comment by RoboticsYimingLi** [comment]
Our query proposal network employs LMSCNet, which takes depth as input and produces 3D occupancy as output. The input depth is obtained from a readily available monocular or binocular depth model.
