### ISSUE TITLE
generate the queries

### ISSUE THREAD

**Issue by Wang0203** [NVlabs/VoxFormer#21]

**Comment by Wang0203** [comment]
how to generate the queries in sequences_msnet3d_sweep10/00/?

**Comment by Wang0203** [comment]
If I follow the preprocess, I can't generate query

**Comment by RoboticsYimingLi** [comment]
Please follow https://github.com/NVlabs/VoxFormer/tree/main/preprocess.

**Comment by Samsara011** [comment]
hello,I also encountered a similar problem. I generated data according to the steps of the document. Why did I generate only the data of voxels but not the data of queries at the end? Have you solved this problem? Look forward to your reply, thank you！
