### ISSUE TITLE
Problem of label_preprocess.py

### ISSUE THREAD

**Issue by JohnFuguiWang** [NVlabs/VoxFormer#29]
Here is the down-sampling code block in label_preprocess.py:
```
for scale in downscaling:
                filename = frame_id + "_" + scale + ".npy"
                label_filename = os.path.join(out_dir, filename)
                # If files have not been created...
                if not os.path.exists(label_filename):
                    if scale == "1_8":
                        LABEL_ds = _downsample_label(
                            LABEL, (256, 256, 32), downscaling[scale]
                        )
                    else:
                        LABEL_ds = LABEL
```
I find that downscaling = {"1_1": 1, "1_2": 2}, which means scale is either "1_1" or "1_2". The program will enter the "else" branch, where LABEL_ds = LABEL, and no downsample is carried out.
So I wonder where is the actual downsample process? Is there a problem or did I just miss something?
Thank you for your respond!

**Comment by RoboticsYimingLi** [comment]
Thank you for reporting this! We have fixed this bug.
