### ISSUE TITLE
No module named 'deform3dattn_custom_cn'

### ISSUE THREAD

**Issue by Made-Gpt** [NVlabs/VoxFormer#44]
Thanks for your great work.

I have issues. I was trying to run 

./tools/dist_test.sh ./projects/configs/voxformer/qpn.py ./path/to/ckpts.pth 1

on my computer, which only has 1 GPU. and the error came as follow：

NotImplementedError: Use sys.path.append here to modify the path to your .so file
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 20568) of binary: /home/made/dep/anaconda/anaconda3/envs/voxformer/bin/python

lt' s located in `multi_scale_deformable_attn_3D_custom_function.py`, where I found the problem: 

 No module named 'deform3dattn_custom_cn'

I have followed every steps in install.md, and maybe the mmdetection3d has some problems, but I could not figure them

**Comment by DzpLab** [comment]
> Thanks for your great work.
> 
> I have issues. I was trying to run
> 
> ./tools/dist_test.sh ./projects/configs/voxformer/qpn.py ./path/to/ckpts.pth 1
> 
> on my computer, which only has 1 GPU. and the error came as follow：
> 
> NotImplementedError: Use sys.path.append here to modify the path to your .so file ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 20568) of binary: /home/made/dep/anaconda/anaconda3/envs/voxformer/bin/python
> 
> lt' s located in `multi_scale_deformable_attn_3D_custom_function.py`, where I found the problem:
> 
> No module named 'deform3dattn_custom_cn'
> 
> I have followed every steps in install.md, and maybe the mmdetection3d has some problems, but I could not figure them

I have the same issues. May I inquire if you've managed to resolve it?

**Comment by Lazyangel** [comment]
You need to comment out the line `# raise NotImplementedError("Use sys.path.append here to modify the path to your .so file")`
 and put your .so file path into the next line`sys.path.append("/path/to/directory_containing_so_file")`
@Duan-AI-study

**Comment by Made-Gpt** [comment]
> You need to comment out the line `# raise NotImplementedError("Use sys.path.append here to modify the path to your .so file")` and put your .so file path into the next line`sys.path.append("/path/to/directory_containing_so_file")` @Duan-AI-study


I resolved it in the same way

**Comment by Unusual6** [comment]
like this : 

(comment)   #_raise NotImplementedError("Use sys.path.append here to modify the path to your .so file")_
sys.path.append("/root/VoxFormer/deform_attn_3d")
