### ISSUE TITLE
when batch_size is not 1?

### ISSUE THREAD

**Issue by Kamp-Sun** [NVlabs/VoxFormer#52]
Hello,

Thank you very much for open-sourcing such a great project. I have a question: when the batch_size is not equal to 1, the number of queries in each batch will be different. How can they be processed in a matrix operation under such circumstances?

**Comment by UQHTy** [comment]
> Hello,
> 
> Thank you very much for open-sourcing such a great project. I have a question: when the batch_size is not equal to 1, the number of queries in each batch will be different. How can they be processed in a matrix operation under such circumstances?

Hi, do you solve this problem? I had the same problem when I changed the training batch to 2.
