### ISSUE TITLE
name 'save_query_path' is not defined

### ISSUE THREAD

**Issue by shuowang666** [NVlabs/VoxFormer#6]
When eval "qpn", it will raise "name 'save_query_path' is not defined". I check line 317 of  lmscnet.py, and find that the defination of "save_query_path" in line 314 is masked. Are there some problems here?

**Comment by RoboticsYimingLi** [comment]
Please comment line 317 (https://github.com/NVlabs/VoxFormer/blob/main/projects/mmdet3d_plugin/voxformer/detectors/lmscnet.py#L317).
