### ISSUE TITLE
如何在个人数据上开始测试？

### ISSUE THREAD

**Issue by iceriver97** [NVlabs/VoxFormer#7]
我想要利用此模型测试对个人数据的效果，而不是使用KITTI数据集，是否有简单的方法？谢谢！

**Comment by iceriver97** [comment]
可以提供一个demo吗？谢谢！

**Comment by SZUshenyan** [comment]
> 最好的方法是将数据转换为与 KITTI 数据集相同的格式。我们正在开发一个用于个性化数据的工具包，完成后将立即发布。

Hello, have you finished yet? Can you publish the code? Thank you very much!

**Comment by Shiyao-Xu** [comment]
Have you guys tried to run the model on Nuscenes dataset?

**Comment by cc1oud** [comment]
> The best way is to convert your data into the same format as the KITTI dataset. We are working on a toolkit for personalized data, and will release it as soon as we finish.

Hi, Have you finished the work...
